spring:
  datasource:
    url: jdbc:mysql://localhost:3306/card?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
mybatis:
  type-aliases-package: com.example.demo.pojo
  

server:
  port: 8888
  
logging: #设置日志级别
  level:
    root: info